#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppVacances.Droid.Resource", IsApplication=true)]

namespace AppVacances.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int athenes1 = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int athenes2 = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int athenes3 = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int athenes4 = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int honolulu1 = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int honolulu2 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int honolulu3 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int honolulu4 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int lisbonne1 = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int lisbonne2 = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int lisbonne3 = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int lisbonne4 = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int londres1 = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int londres2 = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int londres3 = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int londres4 = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int madrid1 = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int madrid2 = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int madrid3 = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int madrid4 = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int newyork1 = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int newyork2 = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int newyork3 = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int newyork4 = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int paris1 = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int paris2 = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int paris3 = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int paris4 = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int rome1 = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int rome2 = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int rome3 = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int rome4 = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int singapour1 = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int singapour2 = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int singapour3 = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int singapour4 = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int tokyo1 = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int tokyo2 = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int tokyo3 = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int tokyo4 = 2130837543;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F030000
			public const int icon = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int icon_round = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int launcher_foreground = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int MainTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
